MvcFerro01/ViewModels/shoeSize/ShoeSizeEditVm.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcFerro01.Entidades;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MvcFerro01.ViewModels.ShoeSize.ShoeSizeEditVm
{
    public class ShoeSizeEditVm
    {
      
   
        public int ShoeSizeId { get; set; }

        [Required(ErrorMessage = "{0} is required")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a {0}")]
        [DisplayName("Shoe")]
        public int ShoeId { get; set; }
        [DisplayName("Size")]
        public int SizeId { get; set; }
        public int QuantityInStock { get; set; }

        [ValidateNever]

        public IEnumerable<SelectListItem> Shoe { get; set; } = null!;
        [ValidateNever]

        public IEnumerable<SelectListItem> Size { get; set; } = null!;


    }
}

MvcFerro01/ViewModels/shoeSize/ShoeSizeListVm.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcFerro01.Entidades;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MvcFerro01.ViewModels.ShoeSize.ShoeSizeListVm
{
    public class ShoeSizeListVm
    {
       public int ShoeSizeId { get; set; }
        public int ShoeId { get; set; }

        public int SizeId { get; set; }

        public Shoes? Shoe { get; set; }
        public Size? Size { get; set; }
        public int QuantityInStock { get; set; }
    }
}

MvcFerro01/Controllers/ShoeSizeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using MvcFerro.Servicios.Interfaces;
using MvcFerro01.Entidades;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcFerro01.ViewModels.ShoeSize.ShoeSizeListVm;
using MvcFerro01.ViewModels.ShoeSize.ShoeSizeEditVm;


namespace MvcFerro01.Controllers
{
    public class ShoeSizeController : Controller
    {
        private readonly IServicioShoeSize? service;
        private readonly IServicioShoes? serviceB;
        private readonly IServicioSize? serviceS;


        private readonly IMapper? _mapper;
        public ShoeSizeController(IServicioShoeSize? BService, IServicioShoes b,IServicioSize S,
            IMapper mapper)
        {
            service = BService;
            _mapper = mapper;
            serviceB = b;
            serviceS = S;
    
        }

        public IActionResult Index(int? page, string? searchTerm = null, bool viewAll = false, int pageSize = 10)
        {

            int pageNumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            IEnumerable<ShoeSize>? shoeS;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    shoeS = service?
                        .GetAll(orderBy: o => o.OrderBy(c => c.Size),
                            filter: c => c.Size.sizeNumber.ToString().Contains(searchTerm),
                propertiesNames: "Shoe,Size");

                    //  || c.BrandName!.Contains(searchTerm));
                    ViewBag.currentSearchTerm = searchTerm;
                }
                else
                {
                    //    brand = service?
                    //      .GetAll(orderBy: o => o.OrderBy(c => c.Descripcion),
                    //                               filter: c => c.Model.Contains(searchTerm),
                    //
                    //      propertiesNames: "Brand,Genre,Sport");

                    shoeS = service?
                     .GetAll(propertiesNames: "Shoe,Size");                        
          //  propertiesNames: "Brand,Genre,Sport");


                }

            }
            else
            {
                shoeS = service?
                    .GetAll(orderBy: o => o.OrderBy(c => c.Size.sizeNumber), propertiesNames: "Shoe,Size");

            }
            

            var BrandVm = _mapper?.Map<List<ShoeSizeListVm>>(shoeS)
                    .ToPagedList(pageNumber, pageSize);


               return View(BrandVm);




            //  int pageNumber = page ?? 1;
            //    int pageSize = 10;
          //  var marca = service?.GetLista();//.ToPagedList(pageNumber, pageSize);
          //  ;
           // return View(marca);
        }
        
        public IActionResult UpSert(int? id)
        {
            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }
            ShoeSizeEditVm shoevm;
            if (id == null || id == 0)
            {
                shoevm = new ShoeSizeEditVm();
                shoevm.Shoe = serviceB!
                    .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                    .Select(c => new SelectListItem
                    {
                        Text = c.Descripcion,
                        Value = c.ShoeId.ToString()
                    }).ToList();
                shoevm.Size = serviceS!
                    .GetAll()
                    .Select(s => new SelectListItem
                    {
                        Text = s.sizeNumber.ToString(),
                        Value = s.SizeId.ToString()
                    }).ToList();
            }
            else
            {
                try
                {
                    ShoeSize? s = service!.Get(c => c.ShoeSizeId == id.Value,
                            propertiesNames: "Shoe,Size");
                    if (s == null)
                    {
                        return NotFound();
                    }
                    s.Shoe = null;
                   s.Size = null;
                    shoevm = _mapper!.Map<ShoeSizeEditVm>(s);

                    shoevm.Shoe = serviceB!
                        .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                        .Select(c => new SelectListItem
                        {
                            Text = c.Descripcion,
                            Value = c.ShoeId.ToString()
                        }).ToList();
                    shoevm.Size = serviceS!
                        .GetAll()
                        .Select(s => new SelectListItem
                        {
                            Text = s.sizeNumber.ToString(),
                            Value = s.SizeId.ToString()
                        }).ToList();

                    return View(shoevm);
                }
                catch (Exception)
                {
                    // Log the exception (ex) here as needed
                    return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while retrieving the record.");
                }

            }
            shoevm.Shoe = serviceB
                .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                .Select(c => new SelectListItem
                {
                    Text = c.Descripcion,
                    Value = c.ShoeId.ToString()
                }).ToList();
            shoevm.Size = serviceS
                .GetAll(orderBy: q => q.OrderBy(c => c.sizeNumber.ToString()))
                .Select(s => new SelectListItem
                {
                    Text = s.sizeNumber.ToString(),
                    Value = s.SizeId.ToString()
                }).ToList();
         
            return View(shoevm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult UpSert(ShoeSizeEditVm shoVm)
        {
            if (!ModelState.IsValid)
            {
                shoVm.Shoe = serviceB!
                                   .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                                   .Select(c => new SelectListItem
                                   {
                                       Text = c.Descripcion,
                                       Value = c.ShoeId.ToString()
                                   }).ToList();
                shoVm.Size = serviceS!
                                  .GetAll(orderBy: q => q.OrderBy(c => c.sizeNumber.ToString()))
                                  .Select(c => new SelectListItem
                                  {
                                      Text = c.sizeNumber.ToString(),
                                      Value = c.SizeId.ToString()
                                  }).ToList();
           
                return View(shoVm);
            }

            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }

            try
            {
                ShoeSize SVm = _mapper.Map<ShoeSize>(shoVm);

                if (service.existe(SVm))
                {
                    shoVm.Shoe = serviceB!
                                 .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                                 .Select(c => new SelectListItem
                                 {
                                     Text = c.Descripcion,
                                     Value = c.ShoeId.ToString()
                                 }).ToList();
                    shoVm.Size = serviceS!
                                      .GetAll(orderBy: q => q.OrderBy(c => c.sizeNumber.ToString()))
                                      .Select(c => new SelectListItem
                                      {
                                          Text = c.sizeNumber.ToString(),
                                          Value = c.SizeId.ToString()
                                      }).ToList();

                    return View(shoVm);
                }
                if (!service.existe(SVm))
                {
                    service.Agregar(SVm);
                    TempData["success"] = "Record successfully added/edited";
                }
                else
                {
                    TempData["Error"] = "Record Exist";
                }
          
           return RedirectToAction("Index");
                
            }
            catch (Exception ex)
            {
                shoVm.Shoe = serviceB!
                              .GetAll(orderBy: q => q.OrderBy(c => c.Descripcion))
                              .Select(c => new SelectListItem
                              {
                                  Text = c.Descripcion,
                                  Value = c.ShoeId.ToString()
                              }).ToList();
                shoVm.Size = serviceS!
                                  .GetAll(orderBy: q => q.OrderBy(c => c.sizeNumber.ToString()))
                                  .Select(c => new SelectListItem
                                  {
                                      Text = c.sizeNumber.ToString(),
                                      Value = c.SizeId.ToString()
                                  }).ToList();
    
                // Log the exception (ex) here as needed
                ModelState.AddModelError(string.Empty, "An error occurred while editing the record.");
                return View(shoVm);
            }
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]

        public IActionResult Delete(int? id)
        {
            if (id is null || id==0)
            {
                return NotFound();
            }
            ShoeSize? shoesize= service?.GetShoeSizePorId(id.Value);

MvcFerro01/Views/ShoeSize/Index.cshtml
@model IPagedList<ShoeSizeListVm>
@using MvcFerro01.Entidades
@using MvcFerro01.ViewModels.ShoeSize.ShoeSizeListVm
@using X.PagedList
@using X.Web.PagedList

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Shoe Size List";
}
@Html.AntiForgeryToken();
<div class="container">
    <div class="row mb-3">
        <div class="col-6">
            <h3>Shoe Size List</h3>

        </div>
        <div class="col-6 text-end">
            <a asp-controller="ShoeSize" asp-action="UpSert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>
                Nuevo
            </a>
        </div>
    </div>
    <form method="get" class="form-inline" asp-action="Index">
        <div class="d-flex flex-row align-items-center">
            <div class="col-auto mx-1">
                <label for="pageSize">Show:</label>
            </div>
            <div class="col-auto mx-2">
                <select class="form-select" id="pageSize" name="pageSize" onchange="this.form.submit()" style="width:70px">
                    @{
                        var options = new List<int> { 5, 10, 15, 20 };
                        foreach (var option in options)
                        {
                            if (ViewBag.currentPageSize == option)
                            {
                                <option selected value="@option">@option</option>

                            }
                            else
                            {
                                <option value="@option">@option</option>

                            }
                        }
                    }
                </select>
            </div>
            <div class="col-auto mx-2" style="width: 200px;">
                <input type="text" name="searchTerm" id="searchTerm" class="form-control" placeholder="Search by..." value="@ViewBag.currentSearchTerm" />
            </div>
            <div class="col-auto d-flex">
                <button type="submit" class="btn btn-primary mx-2">
                    <i class="bi bi-search"></i> Search
                </button>
                <button type="submit" class="btn btn-secondary" id="searchTerm=""" name="viewAll" value="true">
                    <i class="bi bi-list"></i> View All
                </button>
            </div>
        </div>
    </form>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th style="width:10%">Shoe Descripcion</th>
                <th style="width:10%">Size</th>
                <th style="width:10%">stock</th>
                <th style="width:15%">Actions</th>

            </tr>
        </thead>
        <tbody>
            @if (Model.Any())
            {
                foreach (var item in Model)
                {
                    
                    <tr id="@item.ShoeSizeId">

                        <td>                      
                            @item.Shoe.Descripcion               
                            </td>
                            <td>                                   
                             @item.Size.sizeNumber                 
                        </td>
                          <td>
                            @item.QuantityInStock
                        </td>
                       
                        <td>
                            <a class="btn btn-warning" asp-controller="ShoeSize" asp-action="UpSert" asp-route-id="@item.ShoeSizeId">
                                <i class="bi bi-pencil-square"></i>&nbsp;
                                Edit
                            </a>
                            <a onclick="Delete('/shoeSize/Delete/@item.ShoeSizeId',@item.ShoeSizeId)" class="btn btn-danger">
                                <i class="bi bi-trash-fill"></i>
                                Delete
                            </a>
                        </td>
                    </tr>                    
                }
            }
            else
            {
                <tr>
                    <td colspan="2" class="text-center">
                        F?uck!!! No marcas added yet!

                    </td>
                </tr>

            }
        </tbody>
    </table>
    <partial name="_Pager" model="@Model" />
</div>
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/common.js"></script>
}

MvcFerro01/Views/ShoeSize/UpSert.cshtml
@using MvcFerro01.ViewModels.ShoeSize.ShoeSizeEditVm
@model ShoeSizeEditVm
@{
    ViewData["Title"] = "New/Edit ShoeSize";
}
<form method="post" asp-action="UpSert" class="w-75">
    <input type="hidden" asp-for="ShoeSizeId" />

    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">@(Model.ShoeSizeId==0?"Add ShoeSize":"Edit ShoeSize")</h2>

        </div>
        <div class="form-group row py-2">
            <label asp-for="Shoe"></label>
            <select asp-for="ShoeId" asp-items=@Model.Shoe class="form-control">
                <option disabled selected>Select Shoe</option>
            </select>
            <span asp-validation-for="ShoeId" class="text-danger"></span>

        </div>
        <div class="form-group row py-2">
            <label asp-for="Size"></label>
            <select asp-for="SizeId" asp-items=@Model.Size class="form-control">
                <option disabled selected>Select Size</option>
            </select>
            <span asp-validation-for="SizeId" class="text-danger"></span>
        </div>

        <div class="form-group row py-2">
            <label asp-for="QuantityInStock"></label>
            <input asp-for="QuantityInStock" class="form-control" />
            <span asp-validation-for="QuantityInStock" class="text-danger"></span>
        </div>
      
        @if (Model.ShoeSizeId == 0)
        {
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy2-fill"></i>
                Create
            </button>
        }
        else
        {
            <button type="submit" class="btn btn-warning">
                <i class="bi bi-pencil"></i>
                Edit
            </button>

        }
        <a asp-action="Index" class="btn btn-success btn-block">
            <i class="bi bi-backspace"></i>
            Back to List
        </a>


   </div>
    

</form>
@section Scripts
{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
    <!-- Place the following <script> and <textarea> tags your HTML's <body> -->
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount linkchecker',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>
}

MvcFerro01/Views/ShoeSize/UpSert1.cshtml
@using MvcFerro01.ViewModels.ShoeSize.ShoeSizeEditVm
@model ShoeSizeEditVm
@{
    ViewData["Title"] = "New/Edit ShoeSize";
}
<form method="post" asp-action="UpSert1" class="w-75">
    <input type="hidden" asp-for="ShoeSizeId" />

    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">@(Model.ShoeSizeId==0?"Add ShoeSize":"Edit ShoeSize")</h2>

        </div>
        <div class="form-group row py-2">
            <label asp-for="Shoe"></label>
            <select asp-for="ShoeId" asp-items=@Model.Shoe class="form-control">
                <option disabled selected>Select Shoe</option>
            </select>
            <span asp-validation-for="ShoeId" class="text-danger"></span>

        </div>
        <div class="form-group row py-2">
            <label asp-for="Size"></label>
            <select asp-for="SizeId" asp-items=@Model.Size class="form-control">
                <option disabled selected>Select Size</option>
            </select>
            <span asp-validation-for="SizeId" class="text-danger"></span>
        </div>

        <div class="form-group row py-2">
            <label asp-for="QuantityInStock"></label>
            <input asp-for="QuantityInStock" class="form-control" />
            <span asp-validation-for="QuantityInStock" class="text-danger"></span>
        </div>
      
        @if (Model.ShoeSizeId == 0)
        {
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy2-fill"></i>
                Create
            </button>
        }
        else
        {
            <button type="submit" class="btn btn-warning">
                <i class="bi bi-pencil"></i>
                Edit
            </button>

        }
        <a asp-action="Index" class="btn btn-success btn-block">
            <i class="bi bi-backspace"></i>
            Back to List
        </a>


   </div>
    

</form>
@section Scripts
{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
    <!-- Place the following <script> and <textarea> tags your HTML's <body> -->
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount linkchecker',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>
}