MvcFerro01/Controllers/ColorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using MvcFerro.Servicios.Interfaces;
using MvcFerro01.Entidades;
using MvcFerro01.ViewModels.Color.ColorListVm;
using MvcFerro01.ViewModels.Color.ColorEditVm;


namespace MvcFerro01.Controllers
{
    public class ColorController : Controller
    {
        private readonly IServicioColors? service;
        private readonly IMapper? _mapper;
        public ColorController(IServicioColors? BService,
            IMapper mapper)
        {
            service = BService;
            _mapper = mapper;
        }

        public IActionResult Index(int? page, string? searchTerm = null, bool viewAll = false, int pageSize = 10)
        {

            int pageNumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            IEnumerable<Colors>? color;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    color = service?
                        .GetAll(orderBy: o => o.OrderBy(c => c.ColorName),
                            filter: c => c.ColorName.Contains(searchTerm));
                          //  || c.BrandName!.Contains(searchTerm));
                    ViewBag.currentSearchTerm = searchTerm;
                }
                else
                {
                    color = service?
                        .GetAll(orderBy: o => o.OrderBy(c => c.ColorName));

                }

            }
            else
            {
                color = service?
                    .GetAll(orderBy: o => o.OrderBy(c => c.ColorName));

            }
                 var BrandVm = _mapper?.Map<List<ColorListVm>>(color)
                    .ToPagedList(pageNumber, pageSize);


               return View(BrandVm);




            //  int pageNumber = page ?? 1;
            //    int pageSize = 10;
          //  var marca = service?.GetLista();//.ToPagedList(pageNumber, pageSize);
          //  ;
           // return View(marca);
        }
        
        public IActionResult UpSert(int? id)
        {
            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }
            ColorEditVm colorvm;
            if (id == null || id == 0)
            {
                colorvm = new ColorEditVm();
            }
            else
            {
                try
                {
                    Colors? col = service.GetColorsPorId(id.Value);
                    if (col == null)
                    {
                        return NotFound();
                    }
                    colorvm = _mapper.Map<ColorEditVm>(col);
                    return View(colorvm);
                }
                catch (Exception ex)
                {
                    // Log the exception (ex) here as needed
                    return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while retrieving the record.");
                }

            }
            return View(colorvm);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult UpSert(ColorEditVm col)
        {
            if (!ModelState.IsValid)
            {
                return View(col);
            }

            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }

            try
            {
                Colors color = _mapper.Map<Colors>(col);

                if (service.existe(color))
                {
                    ModelState.AddModelError(string.Empty, "Record already exist");
                    return View(col);
                }

                service.Agregar(color);
                TempData["success"] = "Record successfully added/edited";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Log the exception (ex) here as needed
                ModelState.AddModelError(string.Empty, "An error occurred while editing the record.");
                return View(col);
            }
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]

        public IActionResult Delete(int? id)
        {
            if (id is null || id==0)
            {
                return NotFound();
            }
            Colors? color= service?.GetColorsPorId(id.Value);
            if (color is null)
            {
                return NotFound();
            }
            try
            {
                if (service == null || _mapper == null)
                {
                    return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
                }

               // if (service.estarelacionado(category.MarcaId))
                {
               //     return Json(new { success = false, message="Related Record... Delete Deny!!" }); ;
                }
                service.Borrar(color);
                return Json(new { success = true, message = "Record successfully deleted" });
            }
            catch (Exception)
            {

                return Json(new { success = false, message = "Couldn't delete record!!! " }); ;

            }
        }

    }
}

MvcFerro01/Controllers/ShoeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using MvcFerro.Servicios.Interfaces;
using MvcFerro01.Entidades;
using MvcFerro01.ViewModels.Shoe.ShoeListVm;
using MvcFerro01.ViewModels.Shoe.ShoeEditVm;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace MvcFerro01.Controllers
{
    public class ShoeController : Controller
    {
        private readonly IServicioShoes? service;
        private readonly IServicioBrands? serviceB;
        private readonly IServicioGenre? serviceG;
        private readonly IServicioSports? serviceS;

        private readonly IMapper? _mapper;
        public ShoeController(IServicioShoes? BService, IServicioBrands b, IServicioGenre g, IServicioSports s,
            IMapper mapper)
        {
            service = BService;
            _mapper = mapper;
            serviceB = b;
            serviceG = g;
            serviceS = s;
        }

        public IActionResult Index(int? page, string? searchTerm = null, bool viewAll = false, int pageSize = 10)
        {

            int pageNumber = page ?? 1;
            ViewBag.currentPageSize = pageSize;
            IEnumerable<Shoes>? shoe;
            if (!viewAll)
            {
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    shoe = service?
                        .GetAll(orderBy: o => o.OrderBy(c => c.Descripcion),
                            filter: c => c.Model.Contains(searchTerm),
                propertiesNames: "Brand,Genre,Sport");

                    //  || c.BrandName!.Contains(searchTerm));
                    ViewBag.currentSearchTerm = searchTerm;
                }
                else
                {
                    //    brand = service?
                    //      .GetAll(orderBy: o => o.OrderBy(c => c.Descripcion),
                    //                               filter: c => c.Model.Contains(searchTerm),
                    //
                    //      propertiesNames: "Brand,Genre,Sport");

                    shoe = service?
                     .GetAll(propertiesNames: "Brand,Genre,Sport");                        
          //  propertiesNames: "Brand,Genre,Sport");


                }

            }
            else
            {
                shoe = service?
                    .GetAll(orderBy: o => o.OrderBy(c => c.Descripcion), propertiesNames: "Brand,Genre,Sport");

            }
                 var BrandVm = _mapper?.Map<List<ShoeListVm>>(shoe)
                    .ToPagedList(pageNumber, pageSize);


               return View(BrandVm);




            //  int pageNumber = page ?? 1;
            //    int pageSize = 10;
          //  var marca = service?.GetLista();//.ToPagedList(pageNumber, pageSize);
          //  ;
           // return View(marca);
        }
        
        public IActionResult UpSert(int? id)
        {
            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }
            ShoeEditVm shoevm;
            if (id == null || id == 0)
            {
                shoevm = new ShoeEditVm();
                shoevm.Brand = serviceB!
                    .GetAll(orderBy: q => q.OrderBy(c => c.BrandName))
                    .Select(c => new SelectListItem
                    {
                        Text = c.BrandName,
                        Value = c.BrandId.ToString()
                    }).ToList();
                shoevm.Genre = serviceG!
                    .GetAll()
                    .Select(s => new SelectListItem
                    {
                        Text = s.GenreName,
                        Value = s.GenreId.ToString()
                    }).ToList();
                shoevm.Sport = serviceS!
                   .GetAll()
                   .Select(s => new SelectListItem
                   {
                       Text = s.SportName,
                       Value = s.SportId.ToString()
                   }).ToList();
            }
            else
            {
                try
                {
                    Shoes? s = service!.Get(c => c.ShoeId == id.Value,
                            propertiesNames: "Brand,Genre,Sport");
                    if (s == null)
                    {
                        return NotFound();
                    }
                    s.Brand = null;
                   s.Genre = null;
                    s.Sport = null;
                    shoevm = _mapper!.Map<ShoeEditVm>(s);

                    shoevm.Brand = serviceB!
                        .GetAll(orderBy: q => q.OrderBy(c => c.BrandName))
                        .Select(c => new SelectListItem
                        {
                            Text = c.BrandName,
                            Value = c.BrandId.ToString()
                        }).ToList();
                    shoevm.Genre = serviceG!
                        .GetAll()
                        .Select(s => new SelectListItem
                        {
                            Text = s.GenreName,
                            Value = s.GenreId.ToString()
                        }).ToList();
                    shoevm.Sport = serviceS!
                       .GetAll()
                       .Select(s => new SelectListItem
                       {
                           Text = s.SportName,
                           Value = s.SportId.ToString()
                       }).ToList();

                    return View(shoevm);
                }
                catch (Exception)
                {
                    // Log the exception (ex) here as needed
                    return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while retrieving the record.");
                }

            }
            shoevm.Brand = serviceB
                .GetAll(orderBy: q => q.OrderBy(c => c.BrandName))
                .Select(c => new SelectListItem
                {
                    Text = c.BrandName,
                    Value = c.BrandId.ToString()
                }).ToList();
            shoevm.Genre = serviceG
                .GetAll(orderBy: q => q.OrderBy(c => c.GenreName))
                .Select(s => new SelectListItem
                {
                    Text = s.GenreName,
                    Value = s.GenreId.ToString()
                }).ToList();
            shoevm.Sport = serviceS
              .GetAll(orderBy: q => q.OrderBy(c => c.SportName))
              .Select(s => new SelectListItem
              {
                  Text = s.SportName,
                  Value = s.SportId.ToString()
              }).ToList();

            return View(shoevm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult UpSert(ShoeEditVm shoVm)
        {
            if (!ModelState.IsValid)
            {
                shoVm.Brand = serviceB!
                                   .GetAll(orderBy: q => q.OrderBy(c => c.BrandName))
                                   .Select(c => new SelectListItem
                                   {
                                       Text = c.BrandName,
                                       Value = c.BrandId.ToString()
                                   }).ToList();
                shoVm.Genre = serviceG!
                                  .GetAll(orderBy: q => q.OrderBy(c => c.GenreName))
                                  .Select(c => new SelectListItem
                                  {
                                      Text = c.GenreName,
                                      Value = c.GenreId.ToString()
                                  }).ToList();
                shoVm.Sport = serviceS!
                                      .GetAll(orderBy: q => q.OrderBy(c => c.SportName))
                                      .Select(c => new SelectListItem
                                      {
                                          Text = c.SportName,
                                          Value = c.SportId.ToString()
                                      }).ToList();

                return View(shoVm);
            }

            if (service == null || _mapper == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, "Dependencias no están configuradas correctamente");
            }

            try
            {
                Shoes SVm = _mapper.Map<Shoes>(shoVm);

                if (service.existe(SVm))
                {
                    shoVm.Brand = serviceB!
                                 .GetAll(orderBy: q => q.OrderBy(c => c.BrandName))
                                 .Select(c => new SelectListItem
                                 {
                                     Text = c.BrandName,
                                     Value = c.BrandId.ToString()
                                 }).ToList();
                    shoVm.Genre = serviceG!
                                      .GetAll(orderBy: q => q.OrderBy(c => c.GenreName))
                                      .Select(c => new SelectListItem
                                      {
                                          Text = c.GenreName,
                                          Value = c.GenreId.ToString()
                                      }).ToList();
                    shoVm.Sport = serviceS!
                                          .GetAll(orderBy: q => q.OrderBy(c => c.SportName))
                                          .Select(c => new SelectListItem
                                          {
                                              Text = c.SportName,
                                              Value = c.SportId.ToString()
                                          }).ToList();

                    return View(shoVm);
                }

                service.Agregar(SVm);

MvcFerro01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] MVC Ferro </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdn.tiny.cloud/1/ee4otp9ao47w6zc7rvtt4pdkf4mzwi5nzj603z034gzx78i0/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFCoresFerro.Web2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcFerro01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Brand</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sport" asp-action="Index">Sport</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Color" asp-action="Index">Color</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shoe" asp-action="Index">Shoe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoeSize" asp-action="Index">ShoeSize</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcFerro01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcFerro01/Views/Shared/_Pager.cshtml
@model IPagedList
@using X.PagedList
@using X.Web.PagedList
<div class="d-flex">
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page ,
            searchTerm=ViewBag.currentSearchTerm,
            pageSize=ViewBag.currentPageSize,
            filterId=ViewBag.currentFilterId
    }), new PagedListRenderOptions
{
    UlElementClasses = new[] { "pagination" },
    LiElementClasses = new[] { "page-item" },
    PageClasses = new[] { "page-link" },
    DisplayLinkToIndividualPages = true,
    DisplayPageCountAndCurrentLocation = false,
    MaximumPageNumbersToDisplay = 10
})
</div>

MvcFerro01/Views/Shared/_SelectPaginas.cshtml
@{
    int optionSelected = ViewBag.currentPageSize;
}
<select class="form-select" id="pageSize" name="pageSize" onchange="this.form.submit()">
    @{
        var options = new List<int> { 5, 10, 15, 20 };
        foreach (var option in options)
        {
            <option selected="@(optionSelected==option?"selected":null)" value="@option">@option</option>
        }
    }
</select>